POST http://localhost:8080/Produto
Content-Type: application/json

{
  "codigo": 6537,
  "nome": "Smarthphone ASUS Z7",
  "descricao":"Descrição do ASUS",
  "id_lote":{
    "id": 2,
    "dataEntrega": "2022-08-01",
    "observacao": "Produtos Fragéis",
    "id_orgao_donatario": {
      "id": 2,
      "nome": "Hospital das clínicas UFPE",
      "endereco": "Cidade Universitária",
      "telefone": "(81) 2227-7826",
      "horarioFuncionamento": "9h AM e 17h PM",
      "descricao": "Doe"
    },
    "id_orgao_fiscalizador": {
      "id": 2,
      "nome": "Hospital das clínicas UFPE",
      "descricao": "Doe"
    }
  }
}

###

PUT http://localhost:8080/OrgaoDonatario
Content-Type: application/json

{
  "codigo": 6537,
  "nome": "Smarthphone Motorola",
  "descricao":"Descrição do Motorola"
}

###

GET http://localhost:8080/Produto/6537
Content-Type: application/json

###

DELETE http://localhost:8080/Produto/0
Content-Type: application/json


###

GET http://localhost:8080/Produto
Content-Type: application/json